"""
Django settings for Evc_Pj project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os

from pathlib import Path
from dotenv import load_dotenv  # 環境変数管理で.env ファイルを使う

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Tepmpateフォルダへの絶対パスを定義
TEMPLATE_DIR = BASE_DIR / 'Template'

# staticフォルダへの絶対パスを定義
STATIC_DIR = BASE_DIR / 'static'

# メディアフォルダへの絶対パスを定義
MEDIA_DIR = BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-24+dskcldol*5wudumy-w_(ku24h(gwk(-ycl)-9d+tb6db(-1'
# 新しい強力なキーを生成して設定する。
# SECRET_KEY = "50文字以上のランダムな文字列"
# python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
# SECRET_KEY = '+yzll16pb*%eo29fuvsttn4(k(+je(ag3v1rdtj+_7px)z_+4)'
# SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'
# DEBUG = False

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')
# ALLOWED_HOSTS = ['www.sysbevc.com','sysbevc.com']

# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'accounts.apps.AccountsConfig',
    'Evc_App.apps.EvcAppConfig',
    'Evc_Management.apps.EvcManagementConfig',
    'Evc_Owner.apps.EvcOwnerConfig',
    'Fms_Ocrform.apps.EvcOcrformConfig',
    'Fms_fileshare.apps.FmsFileshareConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  #数字の値を3桁のカンマ区切りで表示
    'sequences.apps.SequencesConfig',#django-sequences を追加
]
#最初にリストされているアプリケーションのソースコードが優先される
NUMBER_GROUPING = 3 #数字の値を3桁のカンマ区切りで表示

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'config.Evc_logging_middleware.EvcLoggingMiddleware',
]
X_FRAME_OPTIONS = 'ALLOW'   #<iframe>を利用してPDF等を表示
# クリックジャッキング（透明 iframe による不正操作）の危険があります。
# X_FRAME_OPTIONS = 'DENY'
# 設定なしのデフォルト：SAMEORIGIN 同一オリジンのみ許可（デフォルト）

# DEPLOY = False
DEPLOY = os.getenv('DEPLOY') == 'True'
env_csrf_trusted_origins = os.getenv('CSRF_TRUSTED_ORIGINS')
if env_csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = env_csrf_trusted_origins.split(',')
if DEPLOY:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # USE_X_FORWARDED_HOST = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    # プロキシ越しの場合は必須
    USE_X_FORWARDED_HOST = True    
    # CSRF_TRUSTED_ORIGINS = [
    #     'http://stg.sysbevc.com:8080',
    #     'http://localhost:8080',
    #     'http://127.0.0.1:8080',
    # ]
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    },
    'kmsdatabase': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB_KMS'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'evc_db',
    #     'USER': 'postgres',
    #     'PASSWORD': 'postgres',
    #     'HOST': 'localhost',
    #     'PORT': 5432,
    # },
    # 'kmsdatabase': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'kms_db',
    #     'USER': 'postgres',
    #     'PASSWORD': 'postgres',
    #     'HOST': 'localhost',
    #     'PORT': 5432,
    # },
    # 'kmsdatabase': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}

# 利用するRouter, manage.pyから見ての相対パス
DATABASE_ROUTERS = [
    'Kms_Attendance.db_router.KmsDatabaseRouter',
]
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }          
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True # 日付フォーマット設定

USE_TZ = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240   #  デフォルト値: 1000 フォーム入力の項目数に対応
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR,]         # 開発用
STATIC_ROOT = '/staticfiles'

#MEDIA_DIR
# MEDIA_ROOT = MEDIA_DIR
# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = '/data_root/media'
MEDIA_URL = '/media/'

LOGIN_URL = '/accounts/login/'
# LOGIN_REDIRECT_URL = 'Fms_Ocrform:ocrform'
LOGIN_REDIRECT_URL = 'accounts:redirect_url'
# LOGIN_REDIRECT_URL = 'accounts:mainmenu'
LOGOUT_REDIRECT_URL = '/'

# 環境変数管理で.env ファイルを使う
# load_dotenv(dotenv_path=BASE_DIR / '.env')
env_file = os.getenv('ENV_FILE', '.env')
load_dotenv(BASE_DIR / env_file)

# パスワードリセット機能は、ユーザーにリセット用のリンクをメールで送信する必要があります。
# メール設定を追加します。
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'    # デバッグでコンソール表示
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.EvcUser'

# EVCフォルダへURLパスを定義  baseurl =  f'{self.get_scheme()}://{self.get_netloc()}/'
# Webサーバ（IIS）上に仮想ディレクトリを設定
# EVC_URL = '/EvcData'
# EVCフォルダへの絶対パスを定義(仮想パスに設定した物理パス)

# EVC_ROOT = BASE_DIR / 'Evc_root'
# EVC_ROOT = '/home/yamada/EVC_root'
# EVC_ROOT = 'C:/EVC_root/'
EVC_URL = '/EvcData/'
EVC_HELP_URL = '/help/'
# EVC_HELP_DIR = BASE_DIR / 'Evc_help'
# アップロード先を /data_root に設定
# ( /app の外にあるルート直下の /data_root を指す )
EVC_ROOT = '/data_root/evc_root/'
EVC_HELP_DIR = '/data_root/evc_help/'
# EVC_HELP_DIR = '/home/yamada/Evc_help'
# EVC_HELP_DIR = 'C:/inetpub/wwwroot/EVCsite_py313/Evc_help/'

#Google Cloud Vision APIのの身元証明書のjson
GOOGLE_CLOUD_VISION_KEY = os.getenv('GOOGLE_CLOUD_VISION_KEY')
GOOGLE_OCR = os.getenv('GOOGLE_OCR') == 'True'
#Googleの認証情報
USE_GOOGLE_CALENDAR = True
if USE_GOOGLE_CALENDAR:
    INSTALLED_APPS += (
        'Kms_Calendar.apps.KmsCalendarConfig',
        'Kms_Attendance.apps.KmsAttendanceConfig',
    )

    # ウェブ
    GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI')
    # GOOGLE_REDIRECT_URI = 'http://localhost:8000/calendar/oauth2callback'  # ローカル開発用
    # GOOGLE_REDIRECT_URI = 'https://www.sysbevc.com/calendar/oauth2callback'
    # クライアントシークレットのパス
    # 本番環境では、環境変数か、.envを使って取得
    # 環境変数
    # GOOGLE_CREDENTIALS_FILE = os.environ.get('GOOGLE_CREDENTIALS_FILE')
    # .env
    GOOGLE_CREDENTIALS_FILE = os.getenv('GOOGLE_CREDENTIALS_FILE')
    # GoogleカレンダーAPIのスコープ
    GOOGLE_SCOPES = ['https://www.googleapis.com/auth/calendar.readonly']  # 読み取り専用スコープ

# Django Debug Toolbarの設定
# DEBUG_TOOLBAR = False
# if DEBUG_TOOLBAR:
#     def show_toolbar(request):
#     # ツールバーを表示させる
#         return True
#     INTERNAL_IPS = ['127.0.0.1']

#     INSTALLED_APPS += (
#         'debug_toolbar',
#     )
#     MIDDLEWARE += (
#         'debug_toolbar.middleware.DebugToolbarMiddleware',
#     )
#     DEBUG_TOOLBAR_CONFIG = {
#         'SHOW_TOOLBAR_CALLBACK': show_toolbar,
#     }
#     # DEBUG_TOOLBAR_PANELSに定義した項目のみ表示
#     DEBUG_TOOLBAR_PANELS = [
#         'debug_toolbar.panels.history.HistoryPanel',
#         'debug_toolbar.panels.versions.VersionsPanel',
#         'debug_toolbar.panels.timer.TimerPanel',
#         'debug_toolbar.panels.settings.SettingsPanel',
#         'debug_toolbar.panels.headers.HeadersPanel',
#         'debug_toolbar.panels.request.RequestPanel',
#         'debug_toolbar.panels.sql.SQLPanel',
#         'debug_toolbar.panels.staticfiles.StaticFilesPanel',
#         'debug_toolbar.panels.templates.TemplatesPanel',
#         'debug_toolbar.panels.cache.CachePanel',
#         'debug_toolbar.panels.signals.SignalsPanel',
#         'debug_toolbar.panels.redirects.RedirectsPanel',
#         'debug_toolbar.panels.profiling.ProfilingPanel',
#     ]

LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] '
                      '%(name)s.%(funcName)s:%(lineno)d '
                      '%(message)s'
        },
    },

    'handlers': {
        # Docker標準出力
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },

    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'evc_pj': {   # ← あなたのアプリ名に変更
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}