# Generated by Django 5.2.9 on 2026-04-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtGaikinReport',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('report_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=10, null=True)),
                ('pdf_name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_ym', models.CharField(blank=True, max_length=6, null=True)),
                ('page_count', models.IntegerField(default=0)),
                ('delete_flg', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('create_user', models.CharField(blank=True, max_length=30, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=30, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '外勤報告書情報',
                'verbose_name_plural': '外勤報告書情報',
                'db_table': 'tt_gaikin_report',
                'managed': True,
            },
        ),
    ]
