# Generated by Django 5.2.9 on 2026-06-25 01:13

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaikinReport',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='報告書ID')),
                ('report_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='報告書名')),
                ('owner_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='オーナーID')),
                ('pdf_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='PDFファイル名')),
                ('file_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='ファイルパス')),
                ('processed_ym', models.CharField(blank=True, max_length=6, null=True, verbose_name='処理年月(YYYYMM)')),
                ('page_count', models.IntegerField(default=0, verbose_name='ページ数')),
                ('delete_flg', models.IntegerField(default=0, verbose_name='削除フラグ')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('create_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='作成者')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='作成日時')),
                ('update_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '外勤報告書',
                'verbose_name_plural': '外勤報告書一覧',
                'db_table': 'tr_gaikin_report',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('work_type', models.CharField(choices=[('NORMAL', '出勤'), ('PAID_LEAVE', '有休'), ('AM_LEAVE', '午前半休'), ('PM_LEAVE', '午後半休'), ('COMP_LEAVE', '代休')], default='NORMAL', max_length=20, verbose_name='勤務区分')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name='出勤日時')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='退勤日時')),
                ('break_start', models.DateTimeField(blank=True, null=True, verbose_name='休憩開始日時')),
                ('break_end', models.DateTimeField(blank=True, null=True, verbose_name='休憩終了日時')),
                ('actual_work_hours', models.DurationField(blank=True, null=True, verbose_name='実労働時間')),
                ('overtime_hours', models.DurationField(blank=True, null=True, verbose_name='残業時間')),
                ('break_hours', models.DurationField(blank=True, null=True, verbose_name='休憩時間')),
                ('delete_flg', models.IntegerField(default=0, verbose_name='削除フラグ')),
                ('create_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='作成者')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '勤務実績',
                'verbose_name_plural': '勤務実績一覧',
                'db_table': 'tr_attendance',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='日報対象日')),
                ('work_location', models.CharField(choices=[('OFFICE', '出社（オフィス）'), ('REMOTE', 'リモート（在宅勤務）'), ('OUTSIDE', '直行・直帰（客先など）')], default='OFFICE', max_length=20, verbose_name='勤務場所')),
                ('location_detail', models.CharField(blank=True, help_text='例: 〇〇社 3F 会議室、△△ビル など（直行・直帰時に入力）', max_length=100, null=True, verbose_name='外出先・勤務場所詳細')),
                ('task_summary', models.TextField(verbose_name='業務内容・進捗')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='所感・連絡事項')),
                ('delete_flg', models.IntegerField(default=0, verbose_name='削除フラグ')),
                ('create_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='作成者')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_report', to='attendance.attendance', verbose_name='勤務実績レコード')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '日報',
                'verbose_name_plural': '日報一覧',
                'db_table': 'tr_daily_report',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(verbose_name='年度')),
                ('granted_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='付与日数')),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='取得済み日数')),
                ('delete_flg', models.IntegerField(default=0, verbose_name='削除フラグ')),
                ('create_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='作成者')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '有給残日数',
                'verbose_name_plural': '有給残日数一覧',
                'db_table': 'mt_leave_balance',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', '年月は YYYY-MM 形式で入力してください（例: 2026-06）。')], verbose_name='対象年月')),
                ('total_work_days', models.IntegerField(default=0, verbose_name='総出勤日数')),
                ('total_work_hours', models.DurationField(blank=True, null=True, verbose_name='総実労働時間')),
                ('total_overtime_hours', models.DurationField(blank=True, null=True, verbose_name='総残業時間')),
                ('status', models.CharField(choices=[('UNSUBMITTED', '未提出'), ('SUBMITTED', '提出済（承認待ち）'), ('APPROVED', '確定（承認済み）'), ('REJECTED', '差し戻し')], default='UNSUBMITTED', max_length=20, verbose_name='確定ステータス')),
                ('approval_comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='上長コメント/差し戻し理由')),
                ('delete_flg', models.IntegerField(default=0, verbose_name='削除フラグ')),
                ('create_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='作成者')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '月報',
                'verbose_name_plural': '月報一覧',
                'db_table': 'tr_monthly_report',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(choices=[('OVERTIME', '残業申請'), ('PAID_LEAVE', '有給休暇申請（全休）'), ('AM_LEAVE', '午前半休申請'), ('PM_LEAVE', '午後半休申請'), ('COMP_LEAVE', '代休申請'), ('CORRECTION', '打刻修正申請')], max_length=20, verbose_name='申請種別')),
                ('target_date', models.DateField(verbose_name='対象日')),
                ('corrected_clock_in', models.TimeField(blank=True, null=True, verbose_name='修正後出勤時刻')),
                ('corrected_clock_out', models.TimeField(blank=True, null=True, verbose_name='修正後退勤時刻')),
                ('corrected_break_hours', models.DurationField(blank=True, null=True, verbose_name='修正後休憩時間')),
                ('requested_overtime_hours', models.DurationField(blank=True, null=True, verbose_name='申請残業時間')),
                ('reason', models.TextField(verbose_name='申請理由')),
                ('status', models.CharField(choices=[('PENDING', '未承認（保留中）'), ('APPROVED', '承認済み'), ('REJECTED', '却下')], default='PENDING', max_length=15, verbose_name='承認ステータス')),
                ('approval_comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認・却下理由/コメント')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='承認・却下日時')),
                ('delete_flg', models.IntegerField(default=0, verbose_name='削除フラグ')),
                ('create_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='作成者')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approver', models.ForeignKey(blank=True, db_column='approver_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL, verbose_name='承認者ユーザーID')),
                ('attendance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='attendance.attendance', verbose_name='対象勤務実績')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請ユーザーID')),
            ],
            options={
                'verbose_name': '各種申請',
                'verbose_name_plural': '各種申請一覧',
                'db_table': 'tr_application',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flg', 0)), fields=('user', 'work_date'), name='unique_active_attendance'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flg', 0)), fields=('user', 'report_date'), name='unique_active_daily_report'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flg', 0)), fields=('user', 'fiscal_year'), name='unique_active_leave_balance'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flg', 0)), fields=('user', 'target_month'), name='unique_active_monthly_report'),
        ),
        migrations.AddConstraint(
            model_name='workapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flg', 0)), fields=('user', 'target_date', 'apply_type'), name='unique_active_application'),
        ),
    ]
