# Generated by Django 5.2.9 on 2026-07-06 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workapplication',
            name='unique_active_application',
        ),
        migrations.AddConstraint(
            model_name='workapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flg', 0), models.Q(('status', 'REJECTED'), _negated=True)), fields=('user', 'target_date', 'apply_type'), name='unique_active_application'),
        ),
    ]
